### PR TITLE
Fix ESLint errors

### PR DESCRIPTION
**Pull request by GarrisonD**

### CODE REVIEW

**Comment by faceyspacey** [comment]
cool. why is `minDelay` 1000 now instead of 500? It has to match the css sliding transition durations.

**Comment by GarrisonD** [comment]
i've changed it for checking some things, and forgot to revert changes. thanks!

now everything should be OK! 🙂

**Comment by faceyspacey** [comment]
question: what's the inspiration for changing things like `mapState` to `mapStateToProps` and using less destructuring?

**Comment by GarrisonD** [comment]
I love destructuring a lot. But in these cases `mapStateToProps` has the same style it was described in Redux docs and examples - it will be much more easier to recognize well-known `mapStateToProps` if it has `mapStateToProps` name and the first argument with `state` name.

**Pull request merged**
